apiVersion: v1
kind: Namespace
metadata:
  name: mattermost
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mattermost-config
  namespace: mattermost
data:
  MM_SERVICESETTINGS_SITEURL: "https://mattermost.example.com"
  MM_SQLSETTINGS_DRIVERNAME: "postgres"
  MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:CHANGE_ME@mattermost-db:5432/mattermost?sslmode=disable&connect_timeout=10"
  MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
  MM_PLUGINSETTINGS_DIRECTORY: "./plugins"
  MM_FILESETTINGS_MAXFILESIZE: "52428800"
---
apiVersion: v1
kind: Secret
metadata:
  name: mattermost-db-secret
  namespace: mattermost
type: Opaque
stringData:
  POSTGRES_USER: mmuser
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_DB: mattermost
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-data
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-plugins
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-db
  namespace: mattermost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost-db
  template:
    metadata:
      labels:
        app: mattermost-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        envFrom:
        - secretRef:
            name: mattermost-db-secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: mattermost-db
  namespace: mattermost
spec:
  selector:
    app: mattermost-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
  namespace: mattermost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z mattermost-db 5432; do echo waiting for db; sleep 2; done']
      containers:
      - name: mattermost
        image: mattermost/mattermost-enterprise-edition:latest
        envFrom:
        - configMapRef:
            name: mattermost-config
        ports:
        - containerPort: 8065
          name: http
        volumeMounts:
        - name: mattermost-data
          mountPath: /mattermost/data
        - name: mattermost-plugins
          mountPath: /mattermost/plugins
        - name: mattermost-client-plugins
          mountPath: /mattermost/client/plugins
        livenessProbe:
          httpGet:
            path: /api/v4/system/ping
            port: 8065
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v4/system/ping
            port: 8065
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "2000m"
      volumes:
      - name: mattermost-data
        persistentVolumeClaim:
          claimName: mattermost-data
      - name: mattermost-plugins
        persistentVolumeClaim:
          claimName: mattermost-plugins
      - name: mattermost-client-plugins
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mattermost
  namespace: mattermost
spec:
  selector:
    app: mattermost
  ports:
  - name: http
    port: 8065
    targetPort: 8065
  type: ClusterIP
---
# Optional: Ingress configuration (adjust for your ingress controller)
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mattermost
#   namespace: mattermost
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   ingressClassName: nginx  # or traefik, etc.
#   tls:
#   - hosts:
#     - mattermost.example.com
#     secretName: mattermost-tls
#   rules:
#   - host: mattermost.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: mattermost
#             port:
#               number: 8065
